# Generated by Django 3.2.4 on 2021-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_adress', models.CharField(max_length=100)),
                ('stop_city', models.CharField(max_length=100)),
                ('stop_state', models.CharField(max_length=100)),
                ('stop_date', models.DateField()),
            ],
        ),
    ]
